---
# tasks file for nginx
- name: Установка nginx
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Запуск и автозагрузка nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

