---
# tasks file for php-fpm
- name: install php8.1
  ansible.builtin.apt:
    name: php8.1
    state: present
    install_recommends: no

- name: install php dependence
  ansible.builtin.apt:
    name: 
      - php8.1
      - php8.1-bcmath
      - php8.1-bz2
      - php8.1-cli
      - php8.1-common
      - php8.1-curl
      - php8.1-fpm
      - php8.1-gd
      - php8.1-imagick
      - php8.1-intl
      - php8.1-mbstring
      - php8.1-mysql
      - php8.1-readline
      - php8.1-soap
      - php8.1-xml
      - php8.1-xmlrpc
      - php8.1-zip
    state: present

- name: Edit config php
  ansible.builtin.replace:
        path: /etc/php/8.1/fpm/php.ini
        regexp: ';cgi.fix_pathinfo=1'             
        replace: 'cgi.fix_pathinfo=0'

- name: start and enable php8.1-fpm
  ansible.builtin.service:
    name: php8.1-fpm
    state: started
    enabled: yes