all:
  children:
    web:
      hosts:
        test-noda2:
          ansible_host: 192.168.192.115
        test-noda3:  
          ansible_host: 192.168.192.116
    db:
      hosts:
        test-noda4:
          ansible_host: 192.168.192.112
    lb:
      hosts:
        test-noda5:
          ansible_host: 192.168.192.113