all:
  children:
    web:
      vars:
        wp_db_name: 'wpdb5'
        wp_db_user: 'wpuser5'
        wp_db_pass: 'qwertyWP'
        prefix_db: 'wp6_'
        wp_db_host: '192.168.168.112'
      hosts:
        test-noda2:
          ansible_host: 192.168.192.115
        test-noda3:  
          ansible_host: 192.168.192.116
    db:
      vars:
        allowed_host_to_connect: '0.0.0.0'
        db_name: 'wpdb5'
        db_user: 'wpuser5'
        db_pass: 'qwertyWP'
      hosts:
        test-noda4:
          ansible_host: 192.168.192.112
    lb:
      vars:
        listen_port: 80
        listen_server_name: example.com
        backend_server1: 192.168.192.115
        backend_server2: 192.168.192.116
      hosts:
        test-noda5:
          ansible_host: 192.168.192.113