- name: Install web server
  hosts: web
  become: yes
  roles:
    - nginx

- name: Install php-fpm
  hosts: web
  become: yes
  roles: 
    - php-fpm

- name: Install Mariadb
  hosts: db
  become: yes
  roles: 
    - db

- name: Install wp
  hosts: web
  become: yes
  roles: 
    - wp
