- name: Install web server
  hosts: web
  become: yes
  roles:
    - nginx
    - php-fpm
    - wp

- name: Install Mariadb
  hosts: db
  become: yes
  roles: 
    - db

- name: Install nginx-lb
  hosts: lb
  become: yes
  roles: 
    - nginx-lb

