---
# tasks file for db
- name: install auxiliary packeges
  ansible.builtin.apt:
    name: 
      - software-properties-common
      - dirmngr
      - curl
      - ca-certificates
      - apt-transport-https
      - default-libmysqlclient-dev
      - build-essential
      - pkg-config
      - python3
      - python3-pip
      - python3-dev
    state: latest
    update_cache: yes

- name: install python dependence
  ansible.builtin.pip:
    name: 
      - mysqlclient
    state: present
    executable: pip3

- name: add repository Mariadb
  ansible.builtin.shell: | 
    curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash
  args:
    executable: /bin/bash

- name: install mariadb and dependence
  ansible.builtin.apt:
    name: 
      - libdbi-perl
      - mariadb-client
      - mariadb-server-core
      - socat
      - libhtml-template-perl
      - libmariadb3
      - mariadb-backup
      - mariadb-common
      - mariadb-server
    update_cache: yes

- name: Edit config mariadb
  ansible.builtin.replace:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf 
        regexp: 'bind-address\s*=\s*127.0.0.1'             
        replace: 'bind-address = 0.0.0.0'

- name: start and enable mariadb service 
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes


- name: create db
  community.mysql.mysql_db:
    name: wp-db
    state: present
    # login_unix_socket: /run/mysqld/mysqld.sock

- name: create user
  community.mysql.mysql_user:
    name: wp-user
    password: qwertyWP
    priv: 'wp-db.*:ALL'
    host: '%'
    state: present
    column_case_sensitive: false