---
# tasks file for db
- name: Установка зависимостей
  ansible.builtin.apt:
    name: 
      - software-properties-common
      - dirmngr
      - curl
      - ca-certificates
      - apt-transport-https
    state: latest
    update_cache: yes

- name: Добавления репозитория Mariadb
  ansible.builtin.shell: |
    curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup | bash -s -- --mariadb-server-version="mariadb-11.0"
    args:
      executable: /bin/bash

- name: Установка Mariadb 11
  ansible.builtin.apt:
    name: mariadb-server
    update_cache: yes