---
# tasks file for db
- name: install auxiliary packeges
  ansible.builtin.apt:
    name: 
      - software-properties-common
      - dirmngr
      - curl
      - ca-certificates
      - apt-transport-https
      - default-libmysqlclient-dev
      - build-essential
      - pkg-config
      - python3
      - python3-pip
      - python3-dev
    state: latest
    update_cache: yes

- name: install python dependence
  ansible.builtin.pip:
    name: 
      - mysqlclient
    state: present
    executable: pip3

- name: add repository Mariadb
  ansible.builtin.shell: | 
    curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash
  args:
    executable: /bin/bash

- name: install mariadb and dependence
  ansible.builtin.apt:
    name: 
      - libdbi-perl
      - mariadb-client
      - mariadb-server-core
      - socat
      - libhtml-template-perl
      - libmariadb3
      - mariadb-backup
      - mariadb-common
      - mariadb-server
    update_cache: yes

- name: Edit config mariadb
  ansible.builtin.template:
        src: 50-server.j2
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf           

- name: start and enable mariadb service 
  ansible.builtin.service:
    name: mariadb
    state: restarted
    enabled: yes

- name: create db
  community.mysql.mysql_db:
    name: '{{db_name}}'
    state: present

- name: create user
  community.mysql.mysql_user:
    name: '{{db_user}}'
    password: '{{db_pass}}'
    priv: '{{db_name}}.*:ALL'
    host: '%'
    state: present
    column_case_sensitive: false