---
# tasks file for wp

- name: download wp
  ansible.builtin.get_url:
    url: https://ru.wordpress.org/latest-ru_RU.tar.gz
    dest: /tmp/wp.tar.gz

- name: Extract the archive
  ansible.builtin.unarchive:
    src: /tmp/wp.tar.gz
    dest: /tmp
    remote_src: yes

- name: create directory from wp
  ansible.builtin.file:
    path: /var/www/wp-site/html/
    state: directory

- name: copy wp file in wp-site
  ansible.builtin.copy:
    src: /tmp/wordpress/
    dest: /var/www/wp-site/html/
    remote_src: yes

- name: change owner wp-site
  ansible.builtin.file:
    path: /var/www/wp-site/html/
    state: directory
    owner: www-data
    group: www-data
    recurse: yes

- name: create config wp
  ansible.builtin.template:
    src: wp-config.j2
    dest: /var/www/wp-site/html/wp-config.php

- name: create config web-server nginx
  ansible.builtin.template:
    src: wp-site.j2
    dest: /etc/nginx/sites-available/wp-site.conf
  notify:
    - restart nginx

- name: remove default sim link
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  
- name: create sim link wp-site to site-enabled
  ansible.builtin.file:
    src: /etc/nginx/sites-available/wp-site.conf
    dest: /etc/nginx/sites-enabled/wp-site
    state: link
